
package org.coderic.ws.sunat.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "billValidService", targetNamespace = "http://service.ws.consulta.comppago.electronico.registro.servicio2.sunat.gob.pe/", wsdlLocation = "https://e-factura.sunat.gob.pe/ol-it-wsconsvalidcpe/billValidService?wsdl")
public class BillValidService_Service
    extends Service
{

    private static final URL BILLVALIDSERVICE_WSDL_LOCATION;
    private static final WebServiceException BILLVALIDSERVICE_EXCEPTION;
    private static final QName BILLVALIDSERVICE_QNAME = new QName("http://service.ws.consulta.comppago.electronico.registro.servicio2.sunat.gob.pe/", "billValidService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://e-factura.sunat.gob.pe/ol-it-wsconsvalidcpe/billValidService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BILLVALIDSERVICE_WSDL_LOCATION = url;
        BILLVALIDSERVICE_EXCEPTION = e;
    }

    public BillValidService_Service() {
        super(__getWsdlLocation(), BILLVALIDSERVICE_QNAME);
    }

    public BillValidService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BILLVALIDSERVICE_QNAME, features);
    }

    public BillValidService_Service(URL wsdlLocation) {
        super(wsdlLocation, BILLVALIDSERVICE_QNAME);
    }

    public BillValidService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BILLVALIDSERVICE_QNAME, features);
    }

    public BillValidService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillValidService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BillValidService
     */
    @WebEndpoint(name = "BillValidServicePort")
    public BillValidService getBillValidServicePort() {
        return super.getPort(new QName("http://service.ws.consulta.comppago.electronico.registro.servicio2.sunat.gob.pe/", "BillValidServicePort"), BillValidService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillValidService
     */
    @WebEndpoint(name = "BillValidServicePort")
    public BillValidService getBillValidServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.consulta.comppago.electronico.registro.servicio2.sunat.gob.pe/", "BillValidServicePort"), BillValidService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BILLVALIDSERVICE_EXCEPTION!= null) {
            throw BILLVALIDSERVICE_EXCEPTION;
        }
        return BILLVALIDSERVICE_WSDL_LOCATION;
    }

}
