
package org.coderic.ws.sunat.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "billConsultService", targetNamespace = "http://service.ws.consulta.comppago.electronico.registro.servicio2.sunat.gob.pe/", wsdlLocation = "https://e-factura.sunat.gob.pe/ol-it-wsconscpegem/billConsultService?wsdl")
public class BillConsultService
    extends Service
{

    private static final URL BILLCONSULTSERVICE_WSDL_LOCATION;
    private static final WebServiceException BILLCONSULTSERVICE_EXCEPTION;
    private static final QName BILLCONSULTSERVICE_QNAME = new QName("http://service.ws.consulta.comppago.electronico.registro.servicio2.sunat.gob.pe/", "billConsultService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://e-factura.sunat.gob.pe/ol-it-wsconscpegem/billConsultService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BILLCONSULTSERVICE_WSDL_LOCATION = url;
        BILLCONSULTSERVICE_EXCEPTION = e;
    }

    public BillConsultService() {
        super(__getWsdlLocation(), BILLCONSULTSERVICE_QNAME);
    }

    public BillConsultService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BILLCONSULTSERVICE_QNAME, features);
    }

    public BillConsultService(URL wsdlLocation) {
        super(wsdlLocation, BILLCONSULTSERVICE_QNAME);
    }

    public BillConsultService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BILLCONSULTSERVICE_QNAME, features);
    }

    public BillConsultService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillConsultService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BillService
     */
    @WebEndpoint(name = "BillConsultServicePort")
    public BillService getBillConsultServicePort() {
        return super.getPort(new QName("http://service.ws.consulta.comppago.electronico.registro.servicio2.sunat.gob.pe/", "BillConsultServicePort"), BillService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillService
     */
    @WebEndpoint(name = "BillConsultServicePort")
    public BillService getBillConsultServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.consulta.comppago.electronico.registro.servicio2.sunat.gob.pe/", "BillConsultServicePort"), BillService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BILLCONSULTSERVICE_EXCEPTION!= null) {
            throw BILLCONSULTSERVICE_EXCEPTION;
        }
        return BILLCONSULTSERVICE_WSDL_LOCATION;
    }

}
